# in the future this will generate all the game entities
[entity.enemy]
component = [ "renderable", "movable" ] # repeating fields will only be declared once from the first component that they're found (position)
exclude = [ "color" ] # this member field will not be declared
field.hp = "uint32_t" # fields can be declared directly

[entity.unique.player] # entities in the unique field will not generate a SoA
component = [ "renderable", "movable" ] # repeating fields will only be declared once from the first component that they're found (position)
exclude = [ "color" ] # this member field will not be declared
field.hp = "uint32_t" # fields can be declared directly

[component.renderable]
position         = "struct v2"
size             = "struct v2"
texture_position = "struct v2u"
texture_size     = "struct v2u"
color            = "struct color"

[component.movable]
position = "struct v2"
velocity = "struct v2"
speed    = "float"
