# in the future this will generate all the game entities
[entity.shooter_enemy]
component         = [ "renderable", "movable" ] # repeating fields will only be declared once from the first component that they're found (position)
exclude           = [ "color" ] # if this members exists on a component it'll not be declared
field.hp          = "uint32_t" # fields can be declared directly
field.damage      = "uint32_t"
field.shoot_timer = "float"
field.size        = "float" # you can shadow component fields with the field table

[entity.melee_enemy]
component    = [ "renderable", "movable" ]
exclude      = [ "color" ]
field.hp     = "uint32_t"
field.damage = "uint32_t"
field.size   = "float"

[entity.unique.player] # entities in the unique table will not generate a SoA
component       = [ "renderable", "movable" ]
exclude         = [ "color", "size", "texture_size", "speed" ]
field.hp        = "uint32_t"
field.damage    = "uint32_t"
field.invicible = "float"

[component.renderable]
position         = "struct v2"
size             = "struct v2"
texture_position = "struct v2u"
texture_size     = "struct v2u"
color            = "struct color"

[component.movable]
position = "struct v2"
velocity = "struct v2"
speed    = "float"
